import sqlite3
import uuid


def sanitize(s_input: str):
    return "".join(c for c in s_input if c.isalnum())


class ClientDatabaseHandler:

    def __init__(self, username):
        self.database = None
        self._initialize_database(username)

    def _initialize_database(self, username):
        self.database = sqlite3.connect(f"{username}.db")
        self.database.execute('''CREATE TABLE IF NOT EXIST localUser(
            USERNAME TEXT PRIMARY KEY,
            PASSWORD_HASH TEXT,
            USER_ID INT,
            DECRYPTER TEXT
        )''')
        self.database.execute('''CREATE TABLE IF NOT EXIST contact(
            ID INT PRIMARY KEY,
            USERNAME TEXT
            )''')

    def add_contact(self, user_id, user_name):
        self.database.execute(f'''CREATE TABLE IF NOT EXIST {sanitize(str(user_id))}(
            TIMESTAMP INT PRIMARY KEY,
            MESSAGE TEXT''')
        self.database.execute('''INSERT INTO contact(ID, USERNAME)
            VALUES(?,?)''', (user_id, user_name))
        self.database.commit()

    def add_message(self, user_id, message, timestamp):
        self.database.execute(f'''INSERT INTO {sanitize(str(user_id))}(TIMESTAMP, MESSAGE)
            VALUES(?,?)''', (timestamp, message))

    def add_user(self, username, password_hash, user_id, decrypter):
        """

        :param username:
        :param password_hash:
        :param user_id:
        :param decrypter: decrypter is a key generated by the client and encrypted under the password, used to decrypt
        the stored messages in the messages table
        :return:
        """
        self.database.execute('''INSERT INTO localUser(USERNAME, PASSWORD_HASH, USER_ID, DECRYPTER)
            VALUES(?,?,?,?)''', (username, password_hash, user_id, decrypter))

        self.database.commit()

    def get_user(self, username, password_hash):
        self.database.execute('''SELECT * FROM localUser WHERE USERNAME = ? AND PASSWORD_HASH = ?''',
                              (username, password_hash))


class ServerDatabaseHandler:

    def __init__(self):
        self.database = None
        self.initialize_database()

    def initialize_database(self):
        self.database = sqlite3.connect('credentials.db')
        self.database.execute('''CREATE TABLE IF NOT EXISTS users(
        ID INT PRIMARY KEY,
        USERNAME TEXT,
        KEY TEXT,
        PASSWORD_HASH) ''')

    def insert_new_user(self, username, key, password_hash):
        user_id = uuid.uuid4().int % 1000_0000_0000_0000
        self.database.execute('''INSERT INTO users(ID, USERNAME, KEY, PASSWORD_HASH)
                VALUES(?,?,?,?)''', (user_id, username, key, password_hash))
        self.database.commit()
        return user_id

    def get_user(self, user_id):
        user_request = self.database.execute('''SELECT * FROM users 
            WHERE ID = ? ''', user_id)
        user = {}
        for i in user_request:
            user["user_id"] = i[0]
            user["username"] = i[1]
            user["key"] = i[2]
        return user

    def login(self, username, password_hash):
        user_request = self.database.execute('''SELECT * FROM users 
            WHERE USERNAME = ? AND PASSWORD_HASH = ? ''', (username, password_hash))
        user = {}
        for i in user_request:
            user["user_id"] = i[0]
            user["username"] = i[1]
            user["key"] = i[2]
        return user
